/* WEAKLY TYPED = TIPAGEM FRACA, TIPOS DE DADOS
    JS É TIPAGEM DINAMICA

*/

let qualquer = 'Legal' // DANDO UM VALOR A VARIAVEL
console.log(qualquer) // PRINTANDO NO CONSOLE
console.log(typeof qualquer) // DESCOBRIR O TIPO DA VARIAVEL, STRING

qualquer = 3.123 // DANDO UM VALOR NOVAMENTE A VARIAVEL, RETIRANDO O *LET*
console.log(qualquer) // PRINTANDO NO CONSOLE
console.log(typeof qualquer) // DESCOBRIR O TIPO DA VARIAVEL, NUMBER(INTEIRO OU REAL)


/* EVITAR NOME GENERICOS E SIGLAS PARA SUAS VARIAVEIS

 LET VALOR = '' , MT IMPRECISO

 LET NUMERO = 1 , MT IMPRECISO

 LET PQP = FALSE , PRODUTO QUIMICO PERIGOSO... KKK

 */


